// src/auth/roles.js

export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  REP: "REP",
};

// Define all available permissions
export const PERMISSIONS = {
  // User Management
  VIEW_USERS: "VIEW_USERS",
  CREATE_USER: "CREATE_USER",
  EDIT_USER: "EDIT_USER",
  DELETE_USER: "DELETE_USER",
  
  // REP Management
  VIEW_REPS: "VIEW_REPS",
  CREATE_REP: "CREATE_REP",
  EDIT_REP: "EDIT_REP",
  DELETE_REP: "DELETE_REP",
  
  // Trial Management
  VIEW_TRIALS: "VIEW_TRIALS",
  CREATE_TRIAL: "CREATE_TRIAL",
  EDIT_TRIAL: "EDIT_TRIAL",
  DELETE_TRIAL: "DELETE_TRIAL",
  
  // Work Orders
  VIEW_WORK_ORDERS: "VIEW_WORK_ORDERS",
  CREATE_WORK_ORDER: "CREATE_WORK_ORDER",
  EDIT_WORK_ORDER: "EDIT_WORK_ORDER",
  APPROVE_WORK_ORDER: "APPROVE_WORK_ORDER",
  DELETE_WORK_ORDER: "DELETE_WORK_ORDER",
  
  // Trial Cities
  VIEW_TRIAL_CITIES: "VIEW_TRIAL_CITIES",
  CREATE_TRIAL_CITY: "CREATE_TRIAL_CITY",
  EDIT_TRIAL_CITY: "EDIT_TRIAL_CITY",
  DELETE_TRIAL_CITY: "DELETE_TRIAL_CITY",
  
  // Payments
  VIEW_PAYMENTS: "VIEW_PAYMENTS",
  PROCESS_PAYMENT: "PROCESS_PAYMENT",
  APPROVE_PAYMENT: "APPROVE_PAYMENT",
  
  // Vendor Documents
  VIEW_VENDOR_DOCS: "VIEW_VENDOR_DOCS",
  UPLOAD_VENDOR_DOCS: "UPLOAD_VENDOR_DOCS",
  APPROVE_VENDOR_DOCS: "APPROVE_VENDOR_DOCS",
  
  // Reports
  VIEW_REPORTS: "VIEW_REPORTS",
  EXPORT_REPORTS: "EXPORT_REPORTS",
  
  // Logistics
  VIEW_LOGISTICS: "VIEW_LOGISTICS",
  MANAGE_LOGISTICS: "MANAGE_LOGISTICS",
  
  // ATM Management
  VIEW_ATM: "VIEW_ATM",
  MANAGE_ATM: "MANAGE_ATM",
  
  // Scout Assignment
  VIEW_SCOUTS: "VIEW_SCOUTS",
  ASSIGN_SCOUTS: "ASSIGN_SCOUTS",
};

// Assign permissions to each role
export const ROLE_PERMISSIONS = {
  SUPER_ADMIN: {
    canEdit: true,
    canCreateAdmin: true,
    canCreateREP: true,
    permissions: [
      // Super Admin has ALL permissions
      PERMISSIONS.VIEW_USERS,
      PERMISSIONS.CREATE_USER,
      PERMISSIONS.EDIT_USER,
      PERMISSIONS.DELETE_USER,
      PERMISSIONS.VIEW_REPS,
      PERMISSIONS.CREATE_REP,
      PERMISSIONS.EDIT_REP,
      PERMISSIONS.DELETE_REP,
      PERMISSIONS.VIEW_TRIALS,
      PERMISSIONS.CREATE_TRIAL,
      PERMISSIONS.EDIT_TRIAL,
      PERMISSIONS.DELETE_TRIAL,
      PERMISSIONS.VIEW_WORK_ORDERS,
      PERMISSIONS.CREATE_WORK_ORDER,
      PERMISSIONS.EDIT_WORK_ORDER,
      PERMISSIONS.APPROVE_WORK_ORDER,
      PERMISSIONS.DELETE_WORK_ORDER,
      PERMISSIONS.VIEW_TRIAL_CITIES,
      PERMISSIONS.CREATE_TRIAL_CITY,
      PERMISSIONS.EDIT_TRIAL_CITY,
      PERMISSIONS.DELETE_TRIAL_CITY,
      PERMISSIONS.VIEW_PAYMENTS,
      PERMISSIONS.PROCESS_PAYMENT,
      PERMISSIONS.APPROVE_PAYMENT,
      PERMISSIONS.VIEW_VENDOR_DOCS,
      PERMISSIONS.UPLOAD_VENDOR_DOCS,
      PERMISSIONS.APPROVE_VENDOR_DOCS,
      PERMISSIONS.VIEW_REPORTS,
      PERMISSIONS.EXPORT_REPORTS,
      PERMISSIONS.VIEW_LOGISTICS,
      PERMISSIONS.MANAGE_LOGISTICS,
      PERMISSIONS.VIEW_ATM,
      PERMISSIONS.MANAGE_ATM,
      PERMISSIONS.VIEW_SCOUTS,
      PERMISSIONS.ASSIGN_SCOUTS,
    ],
  },
  ADMIN: {
    canEdit: true,
    canCreateAdmin: false,
    canCreateREP: true,
    permissions: [
      // Admin can do most things except user management
      PERMISSIONS.VIEW_USERS,
      PERMISSIONS.VIEW_REPS,
      PERMISSIONS.CREATE_REP,
      PERMISSIONS.EDIT_REP,
      PERMISSIONS.VIEW_TRIALS,
      PERMISSIONS.CREATE_TRIAL,
      PERMISSIONS.EDIT_TRIAL,
      PERMISSIONS.VIEW_WORK_ORDERS,
      PERMISSIONS.CREATE_WORK_ORDER,
      PERMISSIONS.EDIT_WORK_ORDER,
      PERMISSIONS.VIEW_TRIAL_CITIES,
      PERMISSIONS.CREATE_TRIAL_CITY,
      PERMISSIONS.EDIT_TRIAL_CITY,
      PERMISSIONS.VIEW_PAYMENTS,
      PERMISSIONS.VIEW_VENDOR_DOCS,
      PERMISSIONS.UPLOAD_VENDOR_DOCS,
      PERMISSIONS.VIEW_REPORTS,
      PERMISSIONS.EXPORT_REPORTS,
      PERMISSIONS.VIEW_LOGISTICS,
      PERMISSIONS.VIEW_ATM,
      PERMISSIONS.VIEW_SCOUTS,
      PERMISSIONS.ASSIGN_SCOUTS,
    ],
  },
  REP: {
    canEdit: false,
    canCreateAdmin: false,
    canCreateREP: false,
    permissions: [
      // REP can only view their own data
      PERMISSIONS.VIEW_TRIALS,
      PERMISSIONS.VIEW_WORK_ORDERS,
      PERMISSIONS.VIEW_PAYMENTS,
      PERMISSIONS.VIEW_VENDOR_DOCS,
      PERMISSIONS.VIEW_TRIAL_CITIES,
    ],
  },
};

// 🔹 DUMMY USERS (frontend only)
export const DUMMY_USERS = [
  {
    email: "superadmin@ikf.com",
    password: "123456",
    role: ROLES.SUPER_ADMIN,
    name: "Khushboo",
  },
  {
    email: "admin@ikf.com",
    password: "123456",
    role: ROLES.ADMIN,
    name: "Admin User",
  },
  {
    email: "rep@ikf.com",
    password: "123456",
    role: ROLES.REP,
    name: "REP User",
  },
];